#!/bin/bash

. "$PWD/ENVChecker"
buyerFile=".buyers"
exchangeRate=6.88
getid='0'

add_buyer ()
{
    echo "${1}"
    echo "Please input the new buyer's name:"
    read newbuyer
    echo "His/Her name is: $newbuyer, correct? [y/n]"
    read correct
    
    $(is_buyer_exist "$buyerName")
    if ([ "$correct" = "y" ] || [ "$correct" = "Y" ]) && [ "$getid" = "0" ] 
    then
        uuid="$(uuidgen)"
        echo -e $newbuyer" "$uuid >> $buyerFile
        mkdir -p "$buyerInfoDir/"$uuid
        echo "Buyer_Spent,You_Paid,Deal_Date,Profit,Item" >> "$buyerInfoDir/$uuid/Deals.csv"
        echo
        echo "Added the new buyer \"$newbuyer\""
        echo
    else
        echo "Canceled. Buyer may exist."
    fi
}

log_deal ()
{
    echo "${1}"
    echo "Please input buyer name:"
    read buyerName
    $(is_buyer_exist "$buyerName")
    if [ "$getid" = "0" ]; then 
        echo "Buyer does not exist"
        #TODO give choice to add buyer then continue or list buyers
    else
        echo "Money buyer paid: (RMB)"
        read money_paid
        echo "Money you spent: (USD)"
        read money_spent
        echo "Item: (Optional)"
        read item
        #TODO ask for double check
        DATE=$(date +"%m%d%Y")
        #TODO get current exchange rate
        profit=$(awk "BEGIN {printf \"%.2f\",${money_paid}/${exchangeRate}+${money_spent}}")
        echo -e $money_paid","$money_spent","$DATE","$profit","$item>> "$buyerInfoDir/$getid/Deals.csv"
    fi
}

check_buyer ()
{
    echo "${1}"

    echo "Please input buyer name:"
    read buyerName
    $(is_buyer_exist "$buyerName")
    if [ "$getid" = "0" ]; then 
        echo "Buyer does not exist"
    else
        echo "Buyer $buyerName Record"
        total_profit=0
        {
            while IFS=",": read -r money_paid money_spent DATE profit item
            do
                printf "%-12s | %-12s | %-12s | %-12s | %-12s " "$money_paid" "$money_spent" "$DATE" "$profit" "$item"
                total_profit=$(awk "BEGIN {printf \"%.2f\",${total_profit}+${profit}}")
            done 
        }<"$buyerInfoDir/$getid/Deals.csv"

        echo "Your total profit from $buyerName is: $total_profit"
    fi

}

is_buyer_exist ()
{
    getid='0'
    if [ -f "$buyerFile" ]; then
        while IFS=" ": read -r name uuid
        do
            if [ "$name" = "${1}" ]; then
                getid="$uuid"
                break
            fi
        done <"$buyerFile"
    fi
}