#!/bin/bash

. "$PWD/ENVChecker"
buyerFile=".buyers"

add_buyer ()
{
    echo "${1}"
    echo "Please input the new buyer's name:"
    read newbuyer
    echo "His/Her name is: $newbuyer, correct? [y/n]"
    read correct
    if ([ "$correct" = "y" ] || [ "$correct" = "Y" ]) && [ $(is_buyer_exist "$buyerName") = "0" ] 
    then
        uuid="$(uuidgen)"
        echo -e $newbuyer" "$uuid >> $buyerFile
        mkdir -p "$buyerInfoDir/"$uuid
        echo
        echo "Added the new buyer \"$newbuyer\""
        echo
    else
        echo "Canceled. Buyer may exist."
    fi
}

log_deal ()
{
    echo "${1}"
    echo "Please input buyer name:"
    read buyerName
    getid=$(is_buyer_exist "$buyerName")
    echo "$getid"
    if [ "$getid" = "0" ]; then 
        echo "Buyer does not exist"
        #TODO give choice to add buyer then continue or list buyers
    else
        echo "Money buyer paid: (RMB)"
        read money_paid
        echo "Money you spent: (USD)"
        read money_spent
        echo "Item: (Optional)"
        read item
        #TODO ask for double check
        echo -e $money_paid","$money_spent","$item >> "$buyerInfoDir/$getid/Deals.csv"
    fi
}

check_buyer ()
{
    
}


is_buyer_exist ()
{
    getid='0'
    if [ -f "$buyerFile" ]; then
        while IFS=" ": read -r name uuid
        do
            if [ "$name" = "${1}" ]; then
                getid="$uuid"
                break
            fi
        done <"$buyerFile"
    fi
    echo "$getid"
}